apiVersion: v1
kind: Secret
metadata:
  name: "{{ .clusterId | lower }}-config"
  namespace: "{{ .clusterId | lower }}"
  labels:
    hyperfleet.io/cluster-id: "{{ .clusterId }}"
    hyperfleet.io/resource-type: "secret"
  annotations:
    hyperfleet.io/generation: "{{ .generationId }}"
type: Opaque
stringData:
  apiKey: "Testkey"
  endpoint: "{{ .hyperfleetApiBaseUrl }}"